name: pulfalight
services:
  pulfalight_test_solr:
    type: solr:8.4
    portforward: true
    core: pulfalight-core-test
    app_mount: false
    config:
      dir: "solr/conf"
  pulfalight_development_solr:
    type: solr:8.4
    portforward: true
    core: pulfalight-core-dev
    app_mount: false
    config:
      dir: "solr/conf"
  pulfalight_database:
    type: postgres:15
    portforward: true
    app_mount: false
  pulfalight_redis:
    type: redis:7
    portforward: true
  chrome:
    type: compose
    app_mount: false
    services:
      image: seleniarm/standalone-chromium:114.0
      environment:
        START_XVFB: "true"
        SE_NODE_MAX_SESSIONS: 20
        SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
      logging:
        driver: none
      shm_size: 2G
      ports:
        - "4445:4444"
        - "5900:5900"
        - "7900:7900"
      volumes:
        - /dev/shm:/dev/shm
      command: /opt/bin/entry_point.sh
    portforward: true
proxy:
  pulfalight_test_solr:
    - pulfalight.test.solr.lndo.site:8983
  pulfalight_development_solr:
    - pulfalight.dev.solr.lndo.site:8983
