cotsen: &firestone
  label: 'Firestone Library'
  url: 'https://library.princeton.edu/special-collections/visit-us'
ex: 
  <<: *firestone
gax:
  <<: *firestone
ga:
  <<: *firestone
mss:
  <<: *firestone
njpg:
  <<: *firestone
thx: 
  <<: *firestone
wa:
  <<: *firestone
hsvc:
  <<: *firestone
hsvg:
  <<: *firestone
hsvm:
  <<: *firestone
hsvr:
  <<: *firestone
mudd:
  label: 'Mudd Manuscript Library'
  url: 'https://library.princeton.edu/special-collections/visit-us'
rcppa:
  label: 'ReCAP'
rcppf:
  label: 'ReCAP'
rcpph:
  label: 'ReCAP'
rcpxc:
  label: 'ReCAP'
rcpxg:
  label: 'ReCAP'
rcpxm:
  label: 'ReCAP'
rcpxr:
  label: 'ReCAP'
selectors:
  label: 'ReCAP'
flm:
  <<: *firestone
st:
  label: 'Engineering Library'
  url: "https://library.princeton.edu/engineering"
anxb:
  label: 'Annex B'
ppl:
  label: 'Plasma Physics Library'
