eng: 'Engineering Library'
lae: 'RBSC'
selectors: 'RBSC'
mss: 'RBSC'
rarebooks: 'RBSC'
cotsen: 'RBSC'
ga: 'RBSC'
publicpolicy: 'MUDD'
univarchives: 'MUDD'
mudd: 'MUDD'
rcpph: 'MUDD'
scarcpxm: 'Remote Storage (ReCAP): Manuscripts. Special Collections Use Only'
scactsn: 'Cotsen Children’s Library Archival. Special Collections Use Only'
scagax: 'Graphic Arts Archival. Special Collections Use Only'
scamss: 'Manuscripts Archival. Special Collections Use Only'
scawa: 'Western Americana Archival. Special Collections Use Only'
scaex: 'Rare Books Archival. Special Collections Use Only'
scahsvm: 'Manuscripts Archival. Special Collections Use Only'
scamudd: 'Mudd Archival. Special Collections Use Only'
scathx: 'Theater Archival. Special Collections Use Only'
