development:
  host: localhost
  port: 6379
test:
  host: localhost
  port: 6379
production: &production
  host: <%= ENV['PULFALIGHT_REDIS_URL'] || ENV["REDIS_URL"] || 'localhost' %>
  port: <%= ENV['PULFALIGHT_REDIS_PORT'] || ENV["REDIS_PORT"] || '6379' %>
  db: <%= ENV['PULFALIGHT_REDIS_DB'] || ENV["REDIS_DB"] || 1 %>
  timeout: 30
staging:
  <<: *production
qa:
  <<: *production
