development:
  host: <%= ENV["lando_pulfalight_redis_conn_host"] || "localhost" %>
  port: <%= ENV["lando_pulfalight_redis_conn_port"] || 6379 %>
  db: 0
test:
  host: <%= ENV["lando_pulfalight_redis_conn_host"] || "localhost" %>
  port: <%= ENV["lando_pulfalight_redis_conn_port"] || 6379 %>
  db: 0
production: &production
  host: <%= ENV['PULFALIGHT_REDIS_URL'] || 'localhost' %>
  port: <%= ENV['PULFALIGHT_REDIS_PORT'] || '6379' %>
  db: <%= ENV['PULFALIGHT_REDIS_DB'] || 1 %>
  timeout: 30
staging:
  <<: *production
qa:
  <<: *production
