cotsen:
  name: "Cotsen Children's Library"
  description: "The Cotsen Children's Library is a very special library within the Department of Rare Books and Special Collections at Princeton University Library. Our international research collection of illustrated children's books, manuscripts, original artwork, prints, and educational toys from the 15th century to the present day is the benefaction of Lloyd E. Cotsen '50. The Cotsen Children's Library also has a public face, serving as a resource for children, families, and educators in the greater Princeton area."
  building: 'Firestone Library'
  address1: 'One Washington Road'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08544'
  country: 'USA'
  phone: '(609) 258-1148'
  contact_info: '<a href="https://library.princeton.edu/special-collections/ask-us">Ask Us a Question</a>'
  thumbnail_url: "https://findingaids.princeton.edu/repositories/mss.jpg"
  visit_note: ""

eng:
  name: "Engineering Library"
  description: 'Includes finding aids for collections of technical reports created by various engineering departments and programs at Princeton University from 1947 to 1998, which are housed at the Engineering Library.'
  building: 'Engineering Library'
  address1: 'Engineering Library'
  address2: 'Friend Center for Engineering Education'
  city: 'Princeton'
  state: 'NJ'
  zip: '08540'
  country: 'USA'
  phone: '(609) 258-3200'
  contact_info: 'englib@princeton.edu'
  thumbnail_url: "https://findingaids.princeton.edu/repositories/eng.jpg"
  visit_note: ""

ga:
  name: "Graphic Arts Collection"
  description: "Housed in Firestone Library, the Graphic Arts Collection within the Department of Rare Books and Special Collections includes original prints, drawings, photographs, illustrated books, and printed ephemera from all parts of the world, along with a substantial reference collection on the history of printing and printed books."
  building: 'Firestone Library'
  address1: 'One Washington Road'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08544'
  country: 'USA'
  phone: '(609) 258-3184'
  contact_info: '<a href="https://library.princeton.edu/special-collections/ask-us">Ask Us a Question</a>'
  thumbnail_url: "https://findingaids.princeton.edu/repositories/mss.jpg"
  visit_note: ""

lae:
  name: 'Latin American Ephemera Collections'
  description: "The Princeton University Library has developed numerous collections of Latin American ephemera that are unique in their depth and scope. Privileging the popular voices of the region, the collections document numerous political and social movements, and a wide variety of key socioeconomic and cultural developments."
  building: 'Firestone Library'
  address1: 'One Washington Road'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08544'
  country: 'USA'
  phone: '(609) 258-5964'
  contact_info: '<a href="https://library.princeton.edu/special-collections/ask-us">Ask Us a Question</a>'
  thumbnail_url: "https://findingaids.princeton.edu/repositories/mss.jpg"
  visit_note: ""

mss:
  name: 'Manuscripts Division'
  description: 'Housed in Firestone Library, the Manuscripts Division of the Department of Special Collections includes material documenting 5000 years of recorded history and all parts of the world, with strengths in Western Europe, the Near East, the United States, and Latin America.'
  building: 'Firestone Library'
  address1: 'One Washington Road'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08544'
  country: 'USA'
  phone: '(609) 258-3184'
  contact_info: '<a href="https://library.princeton.edu/special-collections/ask-us">Ask Us a Question</a>'
  thumbnail_url: "https://findingaids.princeton.edu/repositories/mss.jpg"
  visit_note: ""

publicpolicy:
  name: 'Public Policy Papers'
  description: "Housed at the Seeley G. Mudd Manuscript Library, the Public Policy Papers include important collections representing individuals and organizations in the areas of 20th-century American foreign policy, jurisprudence, journalism, public policy formation, and economic development."
  building: 'Seeley G. Mudd Manuscript Library'
  address1: '65 Olden Street'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08540'
  country: 'USA'
  phone: '(609) 258-6345'
  contact_info: '<a href="https://library.princeton.edu/special-collections/ask-us">Ask Us a Question</a>'
  thumbnail_url: "https://findingaids.princeton.edu/repositories/publicpolicy.jpg"
  visit_note: ""

rarebooks:
  name: 'Rare Book Division'
  description: "Housed in Firestone Library, the Rare Book Division of the Department of Special Collections includes printed books, pamphlets, and broadsides, published in early modern Europe as well as 18th and 19th century imprints from the Americas and Europe."
  building: 'Firestone Library'
  address1: 'One Washington Road'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08544'
  country: 'USA'
  phone: '(609) 258-3184'
  contact_info: '<a href="https://library.princeton.edu/special-collections/ask-us">Ask Us a Question</a>'
  thumbnail_url: "https://findingaids.princeton.edu/repositories/mss.jpg"
  visit_note: ""

selectors:
  name: 'General Collections'
  description: "General Collections are teaching and research collections acquired by Princeton University Library subject selectors. The collections cover a wide range of topics related to Princeton University Library's collecting areas."
  building: 'Firestone Library'
  address1: 'General Collections'
  address2: 'One Washington Road'
  city: 'Princeton'
  state: 'NJ'
  zip: '08544'
  country: 'USA'
  phone: '(609) 258-1470'
  contact_info: '<a href="https://library.princeton.edu/special-collections/ask-us">Ask Us a Question</a>'
  thumbnail_url: "https://findingaids.princeton.edu/repositories/mss.jpg"
  visit_note: ""

selectors:
  name: 'General Collections'
  description: "General Collections are teaching and research collections acquired by Princeton University Library subject selectors. The collections cover a wide range of topics related to Princeton University Library's collecting areas."
  building: 'Firestone Library'
  address1: 'General Collections'
  address2: 'One Washington Road'
  city: 'Princeton'
  state: 'NJ'
  zip: '08544'
  country: 'USA'
  phone: '(609) 258-1470'
  contact_info: '<a href="https://library.princeton.edu/special-collections/ask-us">Ask Us a Question</a>'
  thumbnail_url: "https://findingaids.princeton.edu/repositories/mss.jpg"

univarchives:
  name: 'Princeton University Archives'
  building: 'Seeley G. Mudd Manuscript Library'
  address1: 'Seeley G. Mudd Manuscript Library'
  address2: '65 Olden Street'
  city: 'Princeton'
  state: 'NJ'
  zip: '08540'
  country: 'USA'
  phone: '(609) 258-6345'
  contact_info: '<a href="https://library.princeton.edu/special-collections/ask-us">Ask Us a Question</a>'
  thumbnail_url: "https://findingaids.princeton.edu/repositories/univarchives.jpg"
  visit_note: ""

ea:
  name: 'East Asian Collection'
  building: 'Firestone Library'
  address1: 'One Washington Road'
  address2: ''
  city: 'Princeton'
  state: 'NJ'
  zip: '08540'
  country: 'USA'
  phone: ''
  contact_info: '<a href="https://library.princeton.edu/special-collections/ask-us">Ask Us a Question</a>'
  thumbnail_url: "https://findingaids.princeton.edu/repositories/mss.jpg"
  visit_note: ""
