# Configuration file for generation robots.txt

defaults: &defaults
  sitemap_url: https://findingaids.princeton.edu/sitemap.xml
  disallowed_paths:
    - '/*?q=*'
    - '/*?f*'
    - '/bookmarks'
    - '/catalog/*/'
    - '/catalog/email'
    - '/catalog/opensearch'
    - '/catalog/range_limit'
    - '/catalog/sms'
    - '/saved_searches'
    - '/search_history'
    - '/suggest'
    - '/users'
    - '/404'
    - '/422'
    - '/500'
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults
  sitemap_url: https://findingaids-staging.princeton.edu/sitemap.xml

qa:
  <<: *defaults
  sitemap_url: https://findingaids-qa.princeton.edu/sitemap.xml
