---
## Mudd locations temporarily closed.
mudd: &mudd_note >-
  This collection is stored at the Mudd Manuscript Library. Requests will be delivered to the <a href='https://library.princeton.edu/special-collections/mudd'>Special Collections Mudd Reading Room</a>.
rcpph: >-
  This collection is stored at ReCAP. Some or all of this collection is stored offsite, which may delay delivery time. Requests will be delivered to the <a href='https://library.princeton.edu/special-collections/mudd'>Special Collections Mudd Reading Room</a>.
## ReCAP
rcppf: &recap_note >-
  This collection is stored offsite at the ReCAP facility.
rcpxg: *recap_note
rcpxm: *recap_note
rcpxr: *recap_note
rcppa: *recap_note
## Firestone
flm: &firestone_note >-
  This collection is stored onsite at Firestone Library.
flmp: *firestone_note
wa: *firestone_note
gax: *firestone_note
ex: *firestone_note
mss: *firestone_note
ex: *firestone_note
flmm: *firestone_note
ctsn: *firestone_note
thx: *firestone_note
## Vault
hsvc: &firestone_vault >-
  This collection is stored in special vault facilities at Firestone Library.
hsvg: *firestone_vault
hsvm: *firestone_vault
hsvr: *firestone_vault
anxb: "This collection is stored offsite at Annex B (Fine Hall)."
st: "This collection is stored onsite at the Engineering Library."
ppl: "This collection is stored onsite at the Plasma Physics Library."
